#!/usr/bin/env bash
set -e

# You can run it from any directory.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TASK=${@:1}

./gradlew $TASK --daemon --parallel --configure-on-demand --offline -Pdev=true